[theme]

# Primary accent for interactive elements
primaryColor = '#de8cdc'

# Background color for the main content area
backgroundColor = '#5c3252'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#663665'

# Color used for almost all text
textColor = '#ff6eee'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
